#!/usr/bin/env bash

# SEED=1 comment to use rand seed
LX=32
LT=48
TAG="prod"
NCFG=100
NSKIP=10
NTHERM=500
TAU=0.995 # 0.1
NLEAP=20

# "exact_2flav_wilson"
TYPE="one_flavor"
BETA=4.0
KAPPA=0.2380952381
COMPUTE_DIRAC=""
CONN_WEIGHT=1.0
DISC_WEIGHT=1.0
